micronaut:
  server:
    cors:
      enabled: true
      web:
        allowedOrigins:
          http://localhost:4200/
        allowedMethods:
          - POST
          - PUT
          - GET
  application:
    name: servergradle
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/medical_dictionary
    driverClassName: org.postgresql.Driver
    username: vadevid
    password: 'dfg234hj'
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
      packages: "com.example.entity"
    properties:
      hibernate:
        hbm2ddl:
          auto: update

